GCP State 3

diff --git a/.github/workflows/gcp-apply-nic-napv5.yml b/.github/workflows/gcp-apply-nic-napv5.yml
--- a/.github/workflows/gcp-apply-nic-napv5.yml
+++ b/.github/workflows/gcp-apply-nic-napv5.yml
@@ -79,9 +79,6 @@ jobs:
           terraform init \
             -backend-config="bucket=${{ secrets.TF_VAR_GCP_BUCKET_NAME }}"
 
-#      - name: Initialize Terraform
-#        run: terraform init
-
       - name: Terraform Plan
         run: terraform plan -no-color -input=false -out=tfplan
 
@@ -122,9 +119,6 @@ jobs:
           terraform init \
             -backend-config="bucket=${{ secrets.TF_VAR_GCP_BUCKET_NAME }}"
 
-      - name: Initialize Terraform
-        run: terraform init
-
       - name: Terraform Plan
         run: terraform plan -no-color -input=false -out=tfplan
 
@@ -150,21 +144,20 @@ jobs:
         working-directory: ./gcp-test/nap
     steps:
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v3
+
+      - name: Set up Google Cloud Authentication
+        uses: google-github-actions/auth@v2
+        with:
+          credentials_json: ${{ secrets.TF_VAR_GOOGLE_CREDENTIALS }}
 
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3
-        with:
-          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
 
       - name: Initialize Terraform (GCS Backend)
         run: |
           terraform init \
             -backend-config="bucket=${{ secrets.TF_VAR_GCP_BUCKET_NAME }}"
-
-#      - name: Terraform Init
-#        id: init
-#        run: terraform init
 
       - name: Terraform Plan
         if: github.event_name == 'pull_request' || github.event_name == 'push'
@@ -174,7 +167,6 @@ jobs:
             -var="nginx_jwt=${{ secrets.NGINX_JWT }}" \
             -var="nginx_pwd=none"
           terraform show -no-color tfplan > plan.txt
-
 
       - name: Check Changes
         id: check_changes
@@ -189,247 +181,216 @@ jobs:
         if: github.event_name == 'push' && github.ref == 'refs/heads/gcp-apply-nic-napv5' && steps.check_changes.outputs.has_changes == 'true'
         run: terraform apply -auto-approve -lock=false tfplan
 
-#  terraform_policy:
-#    name: "NGINX Policy"
-#    runs-on: ubuntu-latest
-#    needs: terraform_nap
-#    defaults:
-#      run:
-#       working-directory: ./gcp-test/policy
-#    steps:
-#    - name: Checkout
-#      uses: actions/checkout@v4
-#
-#    - name: Setup Terraform
-#      uses: hashicorp/setup-terraform@v3
-#      with:
-#        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
-#
-##    - name: Setup Terraform
-##      uses: hashicorp/setup-terraform@v3
-#
-#    - name: Terraform Init (EKS)
-#      run: |
-#        terraform init
-#      working-directory: ./gcp-test/gke
-#
-#    - name: Print EKS Terraform Outputs
-#      run: terraform output
-#      working-directory: ./gcp-test/gke
-#
-#    - name: Authenticate to Google Cloud
-#      run: |
-#        echo "$TF_VAR_GOOGLE_CREDENTIALS" | gcloud auth activate-service-account --key-file=-
-#        gcloud config set project $TF_VAR_GCP_PROJECT_ID  # Optional, if needed
-#
-#    - name: Fetch GKE Cluster Name and Region
-#      run: |
-#        echo "GKE_CLUSTER_NAME=$data.tfe_outputs.gke.values.kubernetes_cluster_name" >> $GITHUB_ENV
-#        echo "GCP_REGION=$TF_VAR_GCP_REGION" >> $GITHUB_ENV
-#      working-directory: ./gcp-test/gke
-#
-##    - name: Print OS Information
-##      run: uname -a  # Print the full system information
-#
-##    - name: Install kubectl
-##      run: |
-##        curl -LO "https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kubectl"
-##        chmod +x ./kubectl
-##        sudo mv ./kubectl /usr/local/bin/kubectl
-#
-#    - name: Install gke-gcloud-auth-plugin
-#      run: |
-#        sudo apt-get update
-#        sudo apt-get install apt-transport-https ca-certificates gnupg curl
-#        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
-#        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
-#        sudo apt-get update && sudo apt-get install google-cloud-cli
-#        sudo apt-get install google-cloud-cli-gke-gcloud-auth-plugin
-#
-#    - name: Configure kubectl for GKE
-#      run: |
-#        gcloud container clusters get-credentials hk-nic-nap-gke --region $GCP_REGION --project f5-gcs-5611-mktg-secsols
-#
-#    - name: Verify kubectl connectivity
-#      run: kubectl get nodes -n nginx-ingress
-#
-#    - name: Install Docker and Docker Compose
-#      run: |
-#        sudo apt-get update -y
-#        sudo apt-get remove -y containerd containerd.io
-#        sudo apt-get install apt-transport-https ca-certificates curl software-properties-common -y
-#        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
-#        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
-#        sudo apt-get update -y
-#        sudo apt-get install docker-ce docker-ce-cli containerd.io -y
-#        sudo service docker start
-#        sudo usermod -aG docker $USER
-#
-#        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-#        sudo chmod +x /usr/local/bin/docker-compose
-#
-#    - name: Create Certificates Directory for Docker
-#      run: |
-#        sudo mkdir -p /etc/docker/certs.d/private-registry.nginx.com
-#
-#    - name: Create NGINX Repository Certificate for Docker
-#      run: echo "${{ secrets.NGINX_REPO_CRT }}" | sudo tee /etc/docker/certs.d/private-registry.nginx.com/client.cert > /dev/null
-#
-#    - name: Create NGINX Repository Key for Docker
-#      run: echo "${{ secrets.NGINX_REPO_KEY }}" | sudo tee /etc/docker/certs.d/private-registry.nginx.com/client.key > /dev/null
-#
-#    - name: Create Certificates Directory for NGINX
-#      run: |
-#        sudo mkdir -p /etc/ssl/nginx
-#
-#    - name: Save NGINX Repository Certificate for NGINX
-#      run: echo "${{ secrets.NGINX_REPO_CRT }}" | sudo tee /etc/ssl/nginx/nginx-repo.crt > /dev/null
-#
-#    - name: Save NGINX Repository Key for NGINX
-#      run: echo "${{ secrets.NGINX_REPO_KEY }}" | sudo tee /etc/ssl/nginx/nginx-repo.key > /dev/null
-#
-#    - name: Build Docker Image
-#      run: |
-#        docker build --no-cache \
-#          --secret id=nginx-crt,src=/etc/ssl/nginx/nginx-repo.crt \
-#          --secret id=nginx-key,src=/etc/ssl/nginx/nginx-repo.key \
-#          -t waf-compiler-5.4.0:custom .
-#
-#    - name: Ensure correct permissions for nap/charts directory
-#      run: |
-#        sudo chown -R $USER:$USER ${{ github.workspace }}
-#        sudo chmod -R 777 ${{ github.workspace }}
-#
-#    - name: Run Docker Container as Root
-#      run: |
-#        docker run --rm \
-#            -v ${{ github.workspace }}:/workspace \
-#              waf-compiler-5.4.0:custom \
-#            -p /workspace/policy/policy.json -o /workspace/policy/compiled_policy.tgz
-#
-#    - name: Fix permissions for compiled files
-#      run: |
-#        sudo chown -R $USER:$USER ${{ github.workspace }}/policy
-#        chmod 644 ${{ github.workspace }}/policy/compiled_policy.tgz
-#        ls -lh ${{ github.workspace }}/policy
-#
-#
-#    - name: Copy Compiled Policy to NGINX Ingress Controller
-#      run: |
-#        NGINX_POD=$(kubectl get pods -n nginx-ingress -l app.kubernetes.io/name=nginx-ingress -o jsonpath='{.items[0].metadata.name}')
-#        if [ -z "$NGINX_POD" ]; then
-#          echo "Error: NGINX Ingress Controller pod not found!"
-#          exit 1
-#        fi
-#        kubectl cp ${{ github.workspace }}/policy/compiled_policy.tgz $NGINX_POD:/etc/app_protect/bundles/compiled_policy.tgz -n nginx-ingress
-#
-#    - name: Setup Terraform Backend
-#      id: backend
-#      run: |
-#        cat > backend.tf << EOF
-#        terraform {
-#          cloud {
-#            organization = "${{ secrets.TF_CLOUD_ORGANIZATION }}"
-#            workspaces {
-#              name = "${{ secrets.TF_CLOUD_WORKSPACE_POLICY }}"
-#            }
-#          }
-#        }
-#        EOF
-#
-#    - name: Terraform Init
-#      run: |
-#        terraform init
-#
-#    - name: Terraform Plan
-#      run: |
-#        terraform plan -no-color -input=false -out=tfplan
-##        terraform show -no-color tfplan > plan.txt
-#
-#    - name: Check Changes
-#      id: check_changes
-#      run: |
-#        if grep -q "No changes." plan.txt; then
-#          echo "has_changes=false" >> $GITHUB_OUTPUT
-#        else
-#          echo "has_changes=true" >> $GITHUB_OUTPUT
-#        fi
-#
-##    - name: Terraform Apply
-##      if: github.event_name == 'push' && github.ref == 'refs/heads/gcp-apply-nic-napv5' && steps.check_changes.outputs.has_changes == 'true'
-##      run: terraform apply -auto-approve tfplan
-#
-#    - name: Terraform Apply
-#      if: github.ref == 'refs/heads/gcp-apply-nic-napv5' && github.event_name == 'push'
-#      run:
-#        terraform apply -auto-approve -input=false
-#
-#  terraform_arcadia:
-#    name: "Arcadia WebApp"
-#    runs-on: ubuntu-latest
-#    needs: terraform_policy
-#    defaults:
-#      run:
-#        working-directory: ./gcp-test/arcadia
-#    steps:
-#      - name: Checkout
-#        uses: actions/checkout@v4
-#
-#      - name: Setup Terraform
-#        uses: hashicorp/setup-terraform@v3
-#        with:
-#          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
-#
-#      - name: Setup Terraform Backend
-#        id: backend
-#        run: |
-#          cat > backend.tf << EOF
-#          terraform {
-#            cloud {
-#              organization = "${{ secrets.TF_CLOUD_ORGANIZATION }}"
-#              workspaces {
-#                name = "${{ secrets.TF_CLOUD_WORKSPACE_ARCADIA }}"
-#              }
-#            }
-#          }
-#          EOF
-#
-#      - name: Terraform Init
-#        id: init
-#        run: terraform init
-#
-#      - name: Terraform Plan
-#        if: github.event_name == 'pull_request' || github.event_name == 'push'
-#        run: |
-#          terraform plan -no-color -input=false -out=tfplan
-##          terraform show -no-color tfplan > plan.txt
-#
-##      - name: Check Changes
-##        id: check_changes
-##        run: |
-##          if grep -q "No changes." plan.txt; then
-##            echo "has_changes=false" >> $GITHUB_OUTPUT
-##          else
-##            echo "has_changes=true" >> $GITHUB_OUTPUT
-##          fi
-#
-##      - name: Terraform Apply
-##        if: github.event_name == 'push' && github.ref == 'refs/heads/apply-nic-napv5' && steps.check_changes.outputs.has_changes == 'true'
-##        run: terraform apply -auto-approve tfplan
-#
-#      - name: Terraform Apply
-#        if: github.ref == 'refs/heads/gcp-apply-nic-napv5' && github.event_name == 'push'
-#        run: terraform apply -auto-approve -input=false
-#
-#      - name: Get Terraform Outputs
-#        run: |
-#          terraform output -json > outputs.json
-#          EXTERNAL_NAME=$(jq -r '.external_name.value // empty' outputs.json)
-#
-#          if [ -z "$EXTERNAL_NAME" ]; then
-#            echo "::warning::No external_name output found"
-#          else
-#            echo "external_name=$EXTERNAL_NAME" >> $GITHUB_ENV
-#            echo "NGINX Ingress External Name: $EXTERNAL_NAME"
-#          fi
+  terraform_policy:
+    name: "NGINX Policy"
+    runs-on: ubuntu-latest
+    needs: terraform_nap
+    defaults:
+      run:
+       working-directory: ./gcp-test/policy
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
 
+    - name: Set up Google Cloud Authentication
+      uses: google-github-actions/auth@v2
+      with:
+        credentials_json: ${{ secrets.TF_VAR_GOOGLE_CREDENTIALS }}
+
+    - name: Setup Terraform
+      uses: hashicorp/setup-terraform@v3
+
+    - name: Terraform Init (GKE)
+      run: |
+        terraform init
+      working-directory: ./gcp-test/gke
+
+    - name: Print EKS Terraform Outputs
+      run: terraform output
+      working-directory: ./gcp-test/gke
+
+    - name: Authenticate to Google Cloud
+      run: |
+        echo "$TF_VAR_GOOGLE_CREDENTIALS" | gcloud auth activate-service-account --key-file=-
+        gcloud config set project $TF_VAR_GCP_PROJECT_ID  # Optional, if needed
+
+    - name: Fetch GKE Cluster Name and Region
+      run: |
+        echo "GKE_CLUSTER_NAME=$data.terraform_remote_state.gke.outputs.kubernetes_cluster_name" >> $GITHUB_ENV
+        echo "GCP_REGION=$TF_VAR_GCP_REGION" >> $GITHUB_ENV
+      working-directory: ./gcp-test/gke
+
+#    - name: Print OS Information
+#      run: uname -a  # Print the full system information
+
+#    - name: Install kubectl
+#      run: |
+#        curl -LO "https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kubectl"
+#        chmod +x ./kubectl
+#        sudo mv ./kubectl /usr/local/bin/kubectl
+
+    - name: Install gke-gcloud-auth-plugin
+      run: |
+        sudo apt-get update
+        sudo apt-get install apt-transport-https ca-certificates gnupg curl
+        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
+        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
+        sudo apt-get update && sudo apt-get install google-cloud-cli
+        sudo apt-get install google-cloud-cli-gke-gcloud-auth-plugin
+
+    - name: Configure kubectl for GKE
+      run: |
+        gcloud container clusters get-credentials hk-nic-nap-gke --region $GCP_REGION --project f5-gcs-5611-mktg-secsols
+
+    - name: Verify kubectl connectivity
+      run: kubectl get nodes -n nginx-ingress
+
+    - name: Install Docker and Docker Compose
+      run: |
+        sudo apt-get update -y
+        sudo apt-get remove -y containerd containerd.io
+        sudo apt-get install apt-transport-https ca-certificates curl software-properties-common -y
+        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
+        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
+        sudo apt-get update -y
+        sudo apt-get install docker-ce docker-ce-cli containerd.io -y
+        sudo service docker start
+        sudo usermod -aG docker $USER
+
+        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+        sudo chmod +x /usr/local/bin/docker-compose
+
+    - name: Create Certificates Directory for Docker
+      run: |
+        sudo mkdir -p /etc/docker/certs.d/private-registry.nginx.com
+
+    - name: Create NGINX Repository Certificate for Docker
+      run: echo "${{ secrets.NGINX_REPO_CRT }}" | sudo tee /etc/docker/certs.d/private-registry.nginx.com/client.cert > /dev/null
+
+    - name: Create NGINX Repository Key for Docker
+      run: echo "${{ secrets.NGINX_REPO_KEY }}" | sudo tee /etc/docker/certs.d/private-registry.nginx.com/client.key > /dev/null
+
+    - name: Create Certificates Directory for NGINX
+      run: |
+        sudo mkdir -p /etc/ssl/nginx
+
+    - name: Save NGINX Repository Certificate for NGINX
+      run: echo "${{ secrets.NGINX_REPO_CRT }}" | sudo tee /etc/ssl/nginx/nginx-repo.crt > /dev/null
+
+    - name: Save NGINX Repository Key for NGINX
+      run: echo "${{ secrets.NGINX_REPO_KEY }}" | sudo tee /etc/ssl/nginx/nginx-repo.key > /dev/null
+
+    - name: Build Docker Image
+      run: |
+        docker build --no-cache \
+          --secret id=nginx-crt,src=/etc/ssl/nginx/nginx-repo.crt \
+          --secret id=nginx-key,src=/etc/ssl/nginx/nginx-repo.key \
+          -t waf-compiler-5.4.0:custom .
+
+    - name: Ensure correct permissions for nap/charts directory
+      run: |
+        sudo chown -R $USER:$USER ${{ github.workspace }}
+        sudo chmod -R 777 ${{ github.workspace }}
+
+    - name: Run Docker Container as Root
+      run: |
+        docker run --rm \
+            -v ${{ github.workspace }}:/workspace \
+              waf-compiler-5.4.0:custom \
+            -p /workspace/policy/policy.json -o /workspace/policy/compiled_policy.tgz
+
+    - name: Fix permissions for compiled files
+      run: |
+        sudo chown -R $USER:$USER ${{ github.workspace }}/policy
+        chmod 644 ${{ github.workspace }}/policy/compiled_policy.tgz
+        ls -lh ${{ github.workspace }}/policy
+
+    - name: Copy Compiled Policy to NGINX Ingress Controller
+      run: |
+        NGINX_POD=$(kubectl get pods -n nginx-ingress -l app.kubernetes.io/name=nginx-ingress -o jsonpath='{.items[0].metadata.name}')
+        if [ -z "$NGINX_POD" ]; then
+          echo "Error: NGINX Ingress Controller pod not found!"
+          exit 1
+        fi
+        kubectl cp ${{ github.workspace }}/policy/compiled_policy.tgz $NGINX_POD:/etc/app_protect/bundles/compiled_policy.tgz -n nginx-ingress
+
+    - name: Initialize Terraform (GCS Backend)
+      run: |
+        terraform init \
+          -backend-config="bucket=${{ secrets.TF_VAR_GCP_BUCKET_NAME }}"
+
+    - name: Terraform Plan
+      run: |
+        terraform plan -no-color -input=false -out=tfplan
+        terraform show -no-color tfplan > plan.txt
+
+    - name: Check Changes
+      id: check_changes
+      run: |
+        if grep -q "No changes." plan.txt; then
+          echo "has_changes=false" >> $GITHUB_OUTPUT
+        else
+          echo "has_changes=true" >> $GITHUB_OUTPUT
+        fi
+
+    - name: Terraform Apply
+      if: github.event_name == 'push' && github.ref == 'refs/heads/gcp-apply-nic-napv5' && steps.check_changes.outputs.has_changes == 'true'
+      run: terraform apply -auto-approve tfplan
+
+  terraform_arcadia:
+    name: "Arcadia WebApp"
+    runs-on: ubuntu-latest
+    needs: terraform_policy
+    defaults:
+      run:
+        working-directory: ./gcp-test/arcadia
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: Set up Google Cloud Authentication
+        uses: google-github-actions/auth@v2
+        with:
+          credentials_json: ${{ secrets.TF_VAR_GOOGLE_CREDENTIALS }}
+
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3
+
+      - name: Initialize Terraform (GCS Backend)
+        run: |
+          terraform init \
+            -backend-config="bucket=${{ secrets.TF_VAR_GCP_BUCKET_NAME }}"
+
+      - name: Terraform Validate
+        run: terraform validate -no-color
+
+      - name: Terraform Plan
+        if: github.event_name == 'pull_request' || github.event_name == 'push'
+        run: |
+          terraform plan -no-color -input=false -out=tfplan
+          terraform show -no-color tfplan > plan.txt
+
+      - name: Check Changes
+        id: check_changes
+        run: |
+          if grep -q "No changes." plan.txt; then
+            echo "has_changes=false" >> $GITHUB_OUTPUT
+          else
+            echo "has_changes=true" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Terraform Apply
+        if: github.event_name == 'push' && github.ref == 'refs/heads/gcp-apply-nic-napv5' && steps.check_changes.outputs.has_changes == 'true'
+        run: terraform apply -auto-approve tfplan
+
+      - name: Get Terraform Outputs
+        run: |
+          terraform output -json > outputs.json
+          EXTERNAL_NAME=$(jq -r '.external_name.value // empty' outputs.json)
+    
+          if [ -z "$EXTERNAL_NAME" ]; then
+            echo "::warning::No external_name output found"
+          else
+            echo "external_name=$EXTERNAL_NAME" >> $GITHUB_ENV
+            echo "NGINX Ingress External Name: $EXTERNAL_NAME"
+          fi
